ikuzo_rma_admin:
  resource: |
    section: admin
    alias: ikuzo_rma.rma_request
    templates: "@SyliusAdmin\\Crud"
    permission: true
    redirect: update
    grid: ikuzo_admin_rma_request
    vars:
      all:
        subheader: ikuzo_rma.ui.rma_requests
      index:
        icon: newspaper
  type: sylius.resource

ikuzo_rma_admin_rma_request_accept:
  path: /admin/rma-requests/{id}/accept
  defaults:
    _controller: ikuzo_rma.controller.rma_request::applyStateMachineTransitionAction
    _sylius:
      state_machine:
        graph: ikuzo_rma_request
        transition: accept
      redirect: referer

ikuzo_rma_admin_rma_request_refuse:
  path: /admin/rma-requests/{id}/refuse
  defaults:
    _controller: ikuzo_rma.controller.rma_request::applyStateMachineTransitionAction
    _sylius:
      state_machine:
        graph: ikuzo_rma_request
        transition: refuse
      redirect: referer
