services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  ikuzo_sylius_rma.controller.rma:
    class: Ikuzo\SyliusRMAPlugin\Controller\RMAController
    arguments:
      - '%ikuzo_sylius_rma.reasons%'
    tags: [ 'controller.service_arguments' ]

  ikuzo_rma.listener.menu.admin:
    class: Ikuzo\SyliusRMAPlugin\Menu\AdminMenuBuilder
    tags:
      - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addItems }

  ikuzo_rma.processor.rma_request:
    public: true
    class: Ikuzo\SyliusRMAPlugin\Processor\RMARequestProcessor

  ikuzo_rma.form.extension.channel:
    class: Ikuzo\SyliusRMAPlugin\Form\Extension\ChannelTypeExtension
    tags: ['form.type_extension']