services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  ikuzo_sylius_rma.controller.rma:
    class: Ikuzo\SyliusRMAPlugin\Controller\RMAController
    arguments:
      - '%ikuzo_sylius_rma.reasons%'
    tags: [ 'controller.service_arguments' ]
