services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ikuzo\SyliusRMAPlugin\:
      resource: '../../../src/*'
      exclude: '../../../src/{Entity,Migrations,Tests,Kernel.php}'