
sylius_ui:
  events:
    sylius.admin.channel.form.second_column_content:
      blocks:
        avis_verifies:
          template: '@IkuzoSyliusRMAPlugin/Channel/_form.html.twig'
          priority: 5

sylius_resource:
  resources:
    ikuzo_rma.rma_request:
      driver: doctrine/orm
      classes:
        model: Ikuzo\SyliusRMAPlugin\Entity\RMARequest
        interface: Ikuzo\SyliusRMAPlugin\Entity\RMARequestInterface

sylius_grid:
  templates:
    action:
      send_rma: '@IkuzoSyliusRMAPlugin/Grid/Action/send_rma.html.twig'
      ikuzo_rma_accept: '@IkuzoSyliusRMAPlugin/Grid/Action/accept.html.twig'
      ikuzo_rma_refuse: '@IkuzoSyliusRMAPlugin/Grid/Action/refuse.html.twig'
  grids:
    sylius_shop_account_order:
      actions:
        item:
          rma:
            type: send_rma
            label: ikuzo_rma.ui.send_rma
            options:
              link:
                route: ikuzo_rma_contact_page
                parameters:
                  number: resource.number

    ikuzo_admin_rma_request:
      driver:
        name: doctrine/orm
        options:
          class: Ikuzo\SyliusRMAPlugin\Entity\RMARequest
      fields:
        id:
          type: string
          label: sylius.ui.id
          sortable: ~
        channel:
          type: twig
          label: sylius.ui.channel
          sortable: channel.code
          options:
            template: "@SyliusAdmin/Order/Grid/Field/channel.html.twig"
        order:
          type: twig
          label: sylius.ui.order
          path: order
          sortable: ~
          options:
              template: "@SyliusAdmin/Order/Grid/Field/number.html.twig"
        customer:
          type: twig
          label: sylius.ui.customer
          path: order.customer
          options:
            template: "@SyliusAdmin/Order/Grid/Field/customer.html.twig"
        reason:
          type: twig
          label: ikuzo_rma.ui.reason
          options:
            template: '@IkuzoSyliusRMAPlugin/Grid/Field/reason.html.twig'
        variants:
          type: twig
          label: ikuzo_rma.ui.variants
          options:
            template: '@IkuzoSyliusRMAPlugin/Grid/Field/variants.html.twig'
        comment:
          type: string
          label: ikuzo_rma.ui.comment
        state:
          type: twig
          label: sylius.ui.state
          sortable: ~
          options:
            template: "@SyliusUi/Grid/Field/state.html.twig"
            vars:
              labels: "@IkuzoSyliusRMAPlugin/Label/State"
      actions:
        item:
          ikuzo_rma_accept:
            type: ikuzo_rma_accept
            label: ikuzo_rma.ui.accept
            options:
              link:
                route: ikuzo_rma_admin_rma_request_accept
                parameters:
                  id: resource.id 
          ikuzo_rma_refuse:
            type: ikuzo_rma_refuse
            label: ikuzo_rma.ui.refuse
            options:
              link:
                route: ikuzo_rma_admin_rma_request_refuse
                parameters:
                  id: resource.id 

sylius_mailer:
    emails:
        rma_request:
            enabled: true
            template: '@IkuzoSyliusRMAPlugin\rma-email.html.twig'

ikuzo_sylius_rma:
  reasons:
    damaged: ikuzo_rma.form.reasons.damaged
    wrong_product: ikuzo_rma.form.reasons.wrong_product
    other: ikuzo_rma.form.reasons.other

winzou_state_machine:
  ikuzo_rma_request:
    class: Ikuzo\SyliusRMAPlugin\Entity\RMARequest
    property_path: state
    graph: ikuzo_rma_request
    state_machine_class: "%sylius.state_machine.class%"
    states:
      requested: ~
      accepted: ~
      refused: ~
    transitions:
      accept:
        from: [requested]
        to: accepted
      refuse:
        from: [requested]
        to: refused
    callbacks:
      after:
        ikuzo_rma_accept:
          on: ["accept"]
          do: ["@ikuzo_rma.processor.rma_request", "accept"]
          args: ["object"]
        ikuzo_rma_refuse:
          on: ["refuse"]
          do: ["@ikuzo_rma.processor.rma_request", "refuse"]
          args: ["object"]