
sylius_ui:
  events:
    sylius.admin.channel.form.second_column_content:
      blocks:
        avis_verifies:
          template: '@IkuzoSyliusRMAPlugin/Channel/_form.html.twig'
          priority: 5

sylius_resource:
  resources:
    ikuzo_rma.rma_request:
      driver: doctrine/orm
      classes:
        model: Ikuzo\SyliusRMAPlugin\Entity\RMARequest
        interface: Ikuzo\SyliusRMAPlugin\Entity\RMARequestInterface

sylius_grid:
  templates:
    action:
      send_rma: '@IkuzoSyliusRMAPlugin/Grid/Action/send_rma.html.twig'
  grids:
    sylius_shop_account_order:
      actions:
        item:
          rma:
            type: send_rma
            label: ikuzo_rma.ui.send_rma
            options:
              link:
                route: ikuzo_rma_contact_page
                parameters:
                  number: resource.number

# winzou_state_machine:
#   sylius_order:
#     callbacks:
#       after:
#         sylius_send_avisverifies:
#           on: ["fulfill"]
#           do: ["@ikuzo_sylius_avis_verifies.event_listener.on_order_fulfilled", "sendToAvisVerifies"]
#           args: ["object"]

sylius_mailer:
    emails:
        rma_request:
            subject: RMA request
            enabled: true
            template: '@IkuzoSyliusRMAPlugin\rma-email.txt.twig'

ikuzo_sylius_rma:
  reasons:
    damaged: ikuzo_rma.form.reasons.damaged
    wrong_product: ikuzo_rma.form.reasons.wrong_product
    other: ikuzo_rma.form.reasons.other